arm64: configs: Required flags for qpr3 are enabled
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 5).
For kernel requirements at matrix level 5, Missing config
CONFIG_DEBUG_LIST
CONFIG_UTS_NS
CONFIG_ARM64_SW_TTBR0_PAN